### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by meagar** [JcerelusDev/canvasGame01#4]
All you've provided is a minified one-liner that is impossible for a human to read. This isn't open source, and it's extremely poor form to release this under a BSD-style licence if you're not going to include the source in a readable, useful form.

Nobody should use this library until you release the full unminified source code.

**Comment by JcerelusDev** [comment]
Yes it is open source ,once you can use it for free .
The most important thing i wrote a friendly documentation for the library.
Anybody that wants to use it have to copy the cdn link then read the docs.

**Comment by meagar** [comment]
Nobody should ever use this then. It's not "open source" if you don't provide the source code. Just being free to use doesn't make it open source.
